name: Sqitch PR Checks

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - "main"
jobs:
  sqitch-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Download and Extract Sqitch
        run: wget https://github.com/qoharu/sqitch-bundle/archive/refs/heads/master.zip && unzip master.zip
      - name: Check sqitch version
        run: ./sqitch-bundle-master/bin/sqitch --version
      - name: Deploy
        run: ./sqitch-bundle-master/bin/sqitch deploy db:mysql://root:sqitch_test@mysql:3306/sqitch_test
      - name: Verify
        run: ./sqitch-bundle-master/bin/sqitch verify db:mysql://root:sqitch_test@mysql:3306/sqitch_test
      - name: Revert
        run: ./sqitch-bundle-master/bin/sqitch revert -y db:mysql://root:sqitch_test@mysql:3306/sqitch_test
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: sqitch_test
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: sqitch_test
          MYSQL_PASSWORD: sqitch_test
          MYSQL_ROOT_PASSWORD: sqitch_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
