name: Sqitch PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  sqitch-tests:
    runs-on: ubuntu-latest
    container: squhart/sqitch-builder:1.1.0

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check sqitch version
        run: sqitch --version
      - name: Waiting mysql service to be ready
        run: while ! mysqladmin ping -h127.0.0.1:33360; do sleep 5; done
      - name: Deploy
        run: sqitch deploy db:mysql://root:sqitch_test@127.0.0.1:33306/sqitch_test
      - name: Verify
        run: sqitch verify db:mysql://root:sqitch_test@127.0.0.1:33306/sqitch_test
      - name: Revert
        run: sqitch revert -s db:mysql://root:sqitch_test@127.0.0.1:33306/sqitch_test
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: sqitch_test
          MYSQL_ROOT_PASSWORD: sqitch_test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        